---
- name: Create file Playbook
  hosts: localhost
  tasks:
    - name: Create file
      netology.yandex_cloud_elk.create_file:
        path: ./test_playbook_file.txt
        content: "Some text from a playbook"
